BANKS_SEED = [
    {
        "id": "sbi",
        "name": "State Bank of India",
        "short_name": "SBI",
        "type": "Public",
        "interest_min": 8.5,
        "interest_max": 11.0,
        "max_funding": 100000000,
        "processing_fee_percent": 0.35,
        "min_credit_score": 700,
        "collateral_required": True,
        "supports": ["MSME", "PMEGP", "Mudra", "Stand-Up India", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "India's largest public sector bank. Strong presence across MSME, agriculture and government scheme lending.",
        "why": "Best for PMEGP, Mudra and large-ticket MSME loans with collateral. Wide branch network across India.",
        "min_turnover": 0,
    },
    {
        "id": "bob",
        "name": "Bank of Baroda",
        "short_name": "BoB",
        "type": "Public",
        "interest_min": 8.6,
        "interest_max": 11.5,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "Stand-Up India", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "Public sector bank with strong MSME and women entrepreneur lending programs.",
        "why": "Competitive rates for Mudra and Stand-Up India loans. Good for women entrepreneurs.",
        "min_turnover": 0,
    },
    {
        "id": "canara",
        "name": "Canara Bank",
        "short_name": "Canara",
        "type": "Public",
        "interest_min": 8.7,
        "interest_max": 12.0,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "PMEGP", "Mudra"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "Strong south-India presence with dedicated MSME and agriculture lending desks.",
        "why": "Preferred for MSME manufacturing units in south India.",
        "min_turnover": 0,
    },
    {
        "id": "pnb",
        "name": "Punjab National Bank",
        "short_name": "PNB",
        "type": "Public",
        "interest_min": 8.55,
        "interest_max": 11.75,
        "max_funding": 75000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "PMEGP", "Stand-Up India"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "Major public sector bank with deep MSME network in North India.",
        "why": "Strong reach in Punjab, Delhi, Haryana, UP — good for traders & manufacturers.",
        "min_turnover": 0,
    },
    {
        "id": "union",
        "name": "Union Bank of India",
        "short_name": "Union",
        "type": "Public",
        "interest_min": 8.7,
        "interest_max": 12.0,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Public sector bank actively servicing MSMEs in Maharashtra, Karnataka, Telangana.",
        "why": "Good for service & trading businesses with CGTMSE-backed collateral-free loans.",
        "min_turnover": 0,
    },
    {
        "id": "indian-bank",
        "name": "Indian Bank",
        "short_name": "Indian Bank",
        "type": "Public",
        "interest_min": 8.65,
        "interest_max": 11.9,
        "max_funding": 40000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "PMEGP"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "South-India focused public sector bank with strong PMEGP and Mudra delivery.",
        "why": "Quick disbursal for Mudra Shishu/Kishore loans.",
        "min_turnover": 0,
    },
    {
        "id": "hdfc",
        "name": "HDFC Bank",
        "short_name": "HDFC",
        "type": "Private",
        "interest_min": 10.0,
        "interest_max": 16.0,
        "max_funding": 75000000,
        "processing_fee_percent": 1.5,
        "min_credit_score": 720,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Largest private bank. Fast turnaround for unsecured business loans up to ₹75 lakhs.",
        "why": "Best for established businesses needing unsecured working capital with quick disbursal.",
        "min_turnover": 1500000,
    },
    {
        "id": "icici",
        "name": "ICICI Bank",
        "short_name": "ICICI",
        "type": "Private",
        "interest_min": 10.5,
        "interest_max": 17.0,
        "max_funding": 100000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 720,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Private bank with strong digital onboarding for MSME and business loans.",
        "why": "Quick digital sanction (24-48 hrs) for businesses with GST + Udyam.",
        "min_turnover": 2000000,
    },
    {
        "id": "axis",
        "name": "Axis Bank",
        "short_name": "Axis",
        "type": "Private",
        "interest_min": 10.5,
        "interest_max": 17.5,
        "max_funding": 50000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 720,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital"],
        "industries": ["Service", "Trading", "Manufacturing"],
        "states": ["All India"],
        "description": "Private sector bank with competitive unsecured business loans.",
        "why": "Good for service businesses with strong GST returns and bank statements.",
        "min_turnover": 1500000,
    },
    {
        "id": "kotak",
        "name": "Kotak Mahindra Bank",
        "short_name": "Kotak",
        "type": "Private",
        "interest_min": 11.0,
        "interest_max": 18.0,
        "max_funding": 75000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 725,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital", "Machinery Loan"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Private bank with fast digital MSME loan processing.",
        "why": "Best for businesses needing machinery finance or working capital with clean ITR and GST.",
        "min_turnover": 2000000,
    },
    {
        "id": "idfc-first",
        "name": "IDFC FIRST Bank",
        "short_name": "IDFC FIRST",
        "type": "Private",
        "interest_min": 10.5,
        "interest_max": 17.0,
        "max_funding": 40000000,
        "processing_fee_percent": 1.5,
        "min_credit_score": 700,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital"],
        "industries": ["Service", "Trading", "Manufacturing"],
        "states": ["All India"],
        "description": "Newer private bank with competitive MSME lending rates and faster TAT.",
        "why": "Good alternative to larger private banks — faster processing and lower processing fees.",
        "min_turnover": 1000000,
    },
    {
        "id": "yes-bank",
        "name": "YES Bank",
        "short_name": "YES",
        "type": "Private",
        "interest_min": 11.0,
        "interest_max": 18.0,
        "max_funding": 50000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 700,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital", "CGTMSE"],
        "industries": ["Service", "Trading", "Manufacturing"],
        "states": ["All India"],
        "description": "Private bank offering CGTMSE-backed collateral-free MSME loans.",
        "why": "Good for MSME businesses eligible under CGTMSE wanting unsecured credit.",
        "min_turnover": 1500000,
    },
    {
        "id": "sidbi",
        "name": "SIDBI",
        "short_name": "SIDBI",
        "type": "Development",
        "interest_min": 7.5,
        "interest_max": 10.5,
        "max_funding": 250000000,
        "processing_fee_percent": 0.25,
        "min_credit_score": 650,
        "collateral_required": True,
        "supports": ["MSME", "SMILE", "Startup", "CGTMSE", "Stand-Up India"],
        "industries": ["Manufacturing", "Service", "Startup"],
        "states": ["All India"],
        "description": "Principal development finance institution for MSMEs in India. Lowest interest rates for MSME term loans.",
        "why": "Best for MSMEs needing large term loans (₹10L–₹25Cr) at lowest cost. Direct and indirect lending via SIDBI branches.",
        "min_turnover": 0,
    },
    {
        "id": "nabard",
        "name": "NABARD",
        "short_name": "NABARD",
        "type": "Development",
        "interest_min": 7.0,
        "interest_max": 9.5,
        "max_funding": 50000000,
        "processing_fee_percent": 0.1,
        "min_credit_score": 0,
        "collateral_required": False,
        "supports": ["Agriculture", "Kisan Credit Card", "Rural MSME", "SHG", "FPO"],
        "industries": ["Agriculture", "Dairy", "Fisheries", "Food Processing"],
        "states": ["All India"],
        "description": "India's apex rural finance institution. Refinances rural and agri-allied loans through RRBs and cooperative banks.",
        "why": "Best for farmers, dairy/fisheries/food processing units and rural MSMEs. Apply via local RRB or cooperative bank.",
        "min_turnover": 0,
    },
    {
        "id": "mudra-mfi",
        "name": "Ujjivan Small Finance Bank",
        "short_name": "Ujjivan SFB",
        "type": "Small Finance Bank",
        "interest_min": 11.5,
        "interest_max": 24.0,
        "max_funding": 2500000,
        "processing_fee_percent": 1.0,
        "min_credit_score": 0,
        "collateral_required": False,
        "supports": ["Mudra", "MSME", "Business Loan", "SHG"],
        "industries": ["Service", "Trading", "Manufacturing"],
        "states": ["All India"],
        "description": "Small finance bank specialising in micro and small enterprise lending. No minimum credit score required.",
        "why": "Best for first-time borrowers, women entrepreneurs, or micro businesses without credit history or collateral.",
        "min_turnover": 0,
    },
    {
        "id": "jana-sfb",
        "name": "Jana Small Finance Bank",
        "short_name": "Jana SFB",
        "type": "Small Finance Bank",
        "interest_min": 12.0,
        "interest_max": 26.0,
        "max_funding": 1500000,
        "processing_fee_percent": 1.0,
        "min_credit_score": 0,
        "collateral_required": False,
        "supports": ["Mudra", "MSME", "Business Loan"],
        "industries": ["Service", "Trading"],
        "states": ["All India"],
        "description": "Small finance bank focused on underserved small businesses and micro-entrepreneurs.",
        "why": "Good for micro businesses needing quick working capital without formal credit history.",
        "min_turnover": 0,
    },
    {
        "id": "bajaj-finserv",
        "name": "Bajaj Finserv",
        "short_name": "Bajaj",
        "type": "NBFC",
        "interest_min": 14.0,
        "interest_max": 26.0,
        "max_funding": 50000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 685,
        "collateral_required": False,
        "supports": ["Business Loan", "Machinery Loan", "Working Capital"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "India's leading NBFC for quick unsecured business loans with minimal documentation.",
        "why": "Fastest disbursal (24 hrs) for pre-approved customers. Good for urgent working capital.",
        "min_turnover": 1500000,
    },
    {
        "id": "tata-capital",
        "name": "Tata Capital",
        "short_name": "Tata Capital",
        "type": "NBFC",
        "interest_min": 12.0,
        "interest_max": 22.0,
        "max_funding": 75000000,
        "processing_fee_percent": 2.5,
        "min_credit_score": 700,
        "collateral_required": False,
        "supports": ["Business Loan", "MSME", "Working Capital", "Equipment Finance"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Tata Group NBFC with strong MSME and equipment financing products.",
        "why": "Reliable for machinery and equipment loans; competitive rates for established businesses.",
        "min_turnover": 2000000,
    },
    {
        "id": "lendingkart",
        "name": "Lendingkart",
        "short_name": "Lendingkart",
        "type": "Fintech NBFC",
        "interest_min": 15.0,
        "interest_max": 29.0,
        "max_funding": 5000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 650,
        "collateral_required": False,
        "supports": ["Working Capital", "Business Loan", "MSME"],
        "industries": ["Trading", "Service", "Manufacturing"],
        "states": ["All India"],
        "description": "Fintech NBFC using GST and bank data for fast collateral-free working capital loans.",
        "why": "Best for small traders and service businesses with good GST turnover but limited credit history.",
        "min_turnover": 600000,
    },
    {
        "id": "flexiloans",
        "name": "FlexiLoans",
        "short_name": "FlexiLoans",
        "type": "Fintech NBFC",
        "interest_min": 18.0,
        "interest_max": 36.0,
        "max_funding": 1000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 600,
        "collateral_required": False,
        "supports": ["Working Capital", "Business Loan"],
        "industries": ["Trading", "Service"],
        "states": ["All India"],
        "description": "Fintech lender for very small businesses; quick online process with minimal documentation.",
        "why": "Good for very small businesses (turnover ₹6L+) needing quick micro working capital.",
        "min_turnover": 600000,
    },
    {
        "id": "nedfi",
        "name": "NEDFI",
        "short_name": "NEDFI",
        "type": "Development",
        "interest_min": 8.0,
        "interest_max": 11.0,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 0,
        "collateral_required": True,
        "supports": ["MSME", "Manufacturing", "Startup", "NEF"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["Assam", "Meghalaya", "Manipur", "Mizoram", "Nagaland", "Arunachal Pradesh", "Tripura", "Sikkim"],
        "description": "North Eastern Development Finance Corporation — primary development lender for NE India.",
        "why": "Only DFI focused on North East India. Competitive rates and higher subsidy eligibility for NE businesses.",
        "min_turnover": 0,
    },
]
