SCHEMES_SEED = [
    {
        "id": "pmegp",
        "name": "PMEGP",
        "full_name": "Prime Minister's Employment Generation Programme",
        "description": "Credit-linked subsidy programme for setting up new micro-enterprises in non-farm sector. Helps generate employment opportunities in rural and urban areas.",
        "eligibility": [
            "Individuals above 18 years",
            "Minimum 8th standard pass for projects above 10 lakhs (manufacturing) and 5 lakhs (service)",
            "Self-help groups, institutions registered under Societies Registration Act",
            "Charitable trusts",
        ],
        "benefits": [
            "Margin money subsidy 15-35% of project cost",
            "Higher subsidy for SC/ST/OBC/Minorities/Women/Ex-Servicemen/Physically Handicapped",
            "Loan up to ₹25 lakhs for manufacturing and ₹10 lakhs for service sector",
        ],
        "max_funding": 2500000,
        "max_subsidy_percent": 35,
        "documents": ["Aadhaar Card", "PAN Card", "Project Report", "Caste Certificate (if applicable)", "Educational Qualification Certificate", "Address Proof"],
        "process": "Apply online at kviconline.gov.in → District-level Task Force interview → Bank sanction → Margin money claim",
        "categories": ["MSME", "Manufacturing", "Startup"],
        "states": ["All India"],
        "tags": ["new_business", "manufacturing", "service"],
    },
    {
        "id": "mudra",
        "name": "PMMY (Mudra)",
        "full_name": "Pradhan Mantri MUDRA Yojana",
        "description": "Provides loans up to ₹20 lakhs to non-corporate, non-farm small/micro enterprises through Shishu, Kishore and Tarun categories.",
        "eligibility": [
            "Any Indian citizen with a business plan in non-farm income generating activities",
            "Existing or new micro/small enterprises in manufacturing, trading, services or agri-allied activities",
        ],
        "benefits": [
            "Shishu: Loans up to ₹50,000",
            "Kishore: Loans from ₹50,001 to ₹5 lakhs",
            "Tarun: Loans from ₹5 lakhs to ₹10 lakhs",
            "Tarun Plus: Loans from ₹10 lakhs to ₹20 lakhs",
            "Collateral-free",
        ],
        "max_funding": 2000000,
        "max_subsidy_percent": 0,
        "documents": ["Aadhaar Card", "PAN Card", "Business Proof", "Bank Statements (6 months)", "Quotations / Invoices for asset purchase"],
        "process": "Approach any commercial bank, RRB, small finance bank, NBFC or MFI registered with MUDRA",
        "categories": ["MSME", "Startup", "Manufacturing"],
        "states": ["All India"],
        "tags": ["new_business", "existing_business", "trading", "service", "manufacturing"],
    },
    {
        "id": "standupindia",
        "name": "Stand-Up India",
        "full_name": "Stand-Up India Scheme",
        "description": "Facilitates bank loans between ₹10 lakhs and ₹1 crore to at least one SC/ST and one woman borrower per bank branch for setting up greenfield enterprises.",
        "eligibility": [
            "SC/ST and/or Woman entrepreneurs above 18 years",
            "Only for greenfield (new) enterprises in manufacturing, services, trading or agri-allied",
            "In case of non-individual enterprises, 51% shareholding by SC/ST/Woman",
        ],
        "benefits": [
            "Composite loan from ₹10 lakhs to ₹1 crore",
            "Loan covers 75% of project cost (own contribution 10%, may be reduced)",
            "Repayment up to 7 years with moratorium up to 18 months",
        ],
        "max_funding": 10000000,
        "max_subsidy_percent": 0,
        "documents": ["Aadhaar", "PAN", "Caste Certificate (SC/ST)", "Project Report", "Address Proof", "Educational Qualification"],
        "process": "Apply at standupmitra.in → Get connected to nearest branch → Submit project report → Sanction",
        "categories": ["Women", "MSME", "Manufacturing", "Startup"],
        "states": ["All India"],
        "tags": ["women", "sc_st", "new_business"],
    },
    {
        "id": "cgtmse",
        "name": "CGTMSE",
        "full_name": "Credit Guarantee Fund Trust for Micro and Small Enterprises",
        "description": "Provides collateral-free credit guarantee cover for loans up to ₹5 crore to micro and small enterprises.",
        "eligibility": [
            "Existing or new MSEs in manufacturing or service sector",
            "Loan amount up to ₹5 crore",
            "Udyam registered enterprises preferred",
        ],
        "benefits": [
            "Collateral-free loan up to ₹5 crore",
            "Guarantee cover up to 85% for micro enterprises",
            "Higher coverage for women, SC/ST, and units in NER",
        ],
        "max_funding": 50000000,
        "max_subsidy_percent": 0,
        "documents": ["Udyam Certificate", "GST Registration", "Bank Statements", "Project Report", "Financial Statements (existing units)"],
        "process": "Apply to member lending institution (banks/NBFCs) → MLI underwrites loan → CGTMSE issues guarantee cover",
        "categories": ["MSME", "Manufacturing"],
        "states": ["All India"],
        "tags": ["existing_business", "udyam", "no_collateral"],
    },
    {
        "id": "vishwakarma",
        "name": "PM Vishwakarma",
        "full_name": "Pradhan Mantri Vishwakarma Yojana",
        "description": "End-to-end support to artisans and craftspeople through skill training, toolkit incentive and collateral-free credit support.",
        "eligibility": [
            "Artisans/craftspeople working with hands and tools in 18 trades (carpenter, blacksmith, goldsmith, potter, tailor, etc.)",
            "Minimum 18 years of age",
            "Self-employed in unorganised sector",
        ],
        "benefits": [
            "Skill training stipend ₹500/day",
            "Toolkit incentive of ₹15,000",
            "Collateral-free credit support up to ₹3 lakhs (Tranche 1: ₹1 lakh, Tranche 2: ₹2 lakhs)",
            "Subsidised interest rate of 5%",
        ],
        "max_funding": 300000,
        "max_subsidy_percent": 100,
        "documents": ["Aadhaar Card", "Mobile Number linked with Aadhaar", "Bank Account", "Ration Card"],
        "process": "Register at pmvishwakarma.gov.in via CSC → 3-tier verification → Training → Credit linkage",
        "categories": ["MSME", "Manufacturing"],
        "states": ["All India"],
        "tags": ["artisan", "new_business", "skill"],
    },
    {
        "id": "svanidhi",
        "name": "PM SVANidhi",
        "full_name": "PM Street Vendor's AtmaNirbhar Nidhi",
        "description": "Micro-credit facility for street vendors to resume their livelihoods that were adversely affected during the COVID-19 lockdown.",
        "eligibility": [
            "Street vendors with Certificate of Vending / Identity Card issued by Urban Local Bodies",
            "Vendors identified in survey but not yet issued certificate",
            "Vendors who started business after March 24, 2020 (with Letter of Recommendation)",
        ],
        "benefits": [
            "1st tranche: ₹10,000 collateral-free working capital loan",
            "2nd tranche: ₹20,000 on timely repayment",
            "3rd tranche: ₹50,000",
            "7% interest subsidy",
            "₹1,200/year cashback for digital transactions",
        ],
        "max_funding": 50000,
        "max_subsidy_percent": 7,
        "documents": ["Aadhaar", "Vending Certificate / Letter of Recommendation", "Bank Account"],
        "process": "Apply via pmsvanidhi.mohua.gov.in or CSCs → ULB verification → Bank disbursement",
        "categories": ["MSME"],
        "states": ["All India"],
        "tags": ["street_vendor", "trading"],
    },
    {
        "id": "startupindia",
        "name": "Startup India Seed Fund",
        "full_name": "Startup India Seed Fund Scheme (SISFS)",
        "description": "Financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.",
        "eligibility": [
            "DPIIT-recognized startup, incorporated not more than 2 years ago at the time of application",
            "Startup should have a business idea to develop a product/process/service with market fit",
            "Indian promoter shareholding minimum 51%",
        ],
        "benefits": [
            "Up to ₹20 lakhs grant for proof of concept/prototype/product trials",
            "Up to ₹50 lakhs through convertible debentures/debt/debt-linked instruments for market entry, commercialization",
            "Tax exemptions for eligible startups",
        ],
        "max_funding": 5000000,
        "max_subsidy_percent": 0,
        "documents": ["DPIIT Recognition Certificate", "Incorporation Certificate", "PAN", "Pitch Deck", "Business Plan"],
        "process": "Apply to incubators listed at seedfund.startupindia.gov.in → Incubator evaluation → Grant/debt sanction",
        "categories": ["Startup"],
        "states": ["All India"],
        "tags": ["startup", "dpiit", "new_business"],
    },
    {
        "id": "sidbi-make-in-india",
        "name": "SIDBI Make in India Loan",
        "full_name": "SMILE — SIDBI Make in India Loan for Enterprises",
        "description": "Soft loan to MSMEs in 25 identified sectors to meet equity gap and provide term loan for capital expenditure.",
        "eligibility": [
            "New enterprises in manufacturing and services sector",
            "Existing units undertaking expansion, modernization, technology upgradation",
            "Minimum promoter contribution of 15%",
        ],
        "benefits": [
            "Loans from ₹10 lakhs to ₹25 crores",
            "Repayment up to 10 years including moratorium of 36 months",
            "Soft loan component for filling equity gap",
        ],
        "max_funding": 250000000,
        "max_subsidy_percent": 0,
        "documents": ["Udyam Registration", "Project Report", "Financial Statements", "GST Returns", "ITR"],
        "process": "Apply at SIDBI branch or via sidbi.in → Project appraisal → Sanction",
        "categories": ["MSME", "Manufacturing", "Startup"],
        "states": ["All India"],
        "tags": ["manufacturing", "expansion", "existing_business", "new_business"],
    },
    {
        "id": "gujarat-msme",
        "name": "Gujarat MSME Capital Subsidy",
        "full_name": "Atmanirbhar Gujarat Scheme for Assistance to MSMEs",
        "description": "Capital investment subsidy on fixed capital investment by new and expanding MSMEs in Gujarat.",
        "eligibility": [
            "MSME units (Micro, Small, Medium) registered under Udyam",
            "Manufacturing units in Gujarat",
            "New units or expansion of existing units",
        ],
        "benefits": [
            "Capital subsidy of 10-25% on eligible fixed capital investment based on category & taluka",
            "Interest subsidy 5-7% for 5-7 years",
            "Higher subsidy for women, SC/ST, differently-abled entrepreneurs",
        ],
        "max_funding": 3500000,
        "max_subsidy_percent": 25,
        "documents": ["Udyam Certificate", "GST Registration", "Project Report", "Land Documents", "Pollution Clearance"],
        "process": "Apply via ic.gujarat.gov.in → District Industries Centre verification → Sanction",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Gujarat"],
        "tags": ["manufacturing", "subsidy", "gujarat"],
    },
    {
        "id": "mp-msme",
        "name": "MP MSME Development Scheme",
        "full_name": "Madhya Pradesh MSME Development Policy",
        "description": "Incentives for MSMEs setting up units in Madhya Pradesh including capital investment subsidy and interest subsidy.",
        "eligibility": [
            "Udyam-registered MSME in MP",
            "New manufacturing units or expansion",
        ],
        "benefits": [
            "Capital investment subsidy up to 40% (₹1 crore cap) based on taluka classification",
            "Interest subsidy 5% for 5 years",
            "Stamp duty and electricity duty exemptions",
        ],
        "max_funding": 10000000,
        "max_subsidy_percent": 40,
        "documents": ["Udyam Certificate", "Project Report", "Land Documents", "MPIDC approval"],
        "process": "Apply via mpmsme.gov.in → DIC verification → State Level Empowered Committee approval",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Madhya Pradesh"],
        "tags": ["manufacturing", "subsidy", "mp"],
    },
    {
        "id": "maharashtra-msme",
        "name": "Maharashtra PSI",
        "full_name": "Maharashtra Package Scheme of Incentives (PSI) for MSMEs",
        "description": "Industrial promotion scheme offering incentives like capital subsidy, interest subsidy, and tax incentives to MSMEs in Maharashtra.",
        "eligibility": [
            "Udyam-registered Micro, Small or Medium enterprises in Maharashtra",
            "New or expansion projects in manufacturing",
        ],
        "benefits": [
            "Industrial Promotion Subsidy up to 100% of fixed capital investment over 7-10 years",
            "Interest subsidy 5% on term loans for 5 years",
            "Electricity duty exemption",
            "Stamp duty waiver",
        ],
        "max_funding": 50000000,
        "max_subsidy_percent": 100,
        "documents": ["Udyam Certificate", "DIC EM-II", "Project Report", "Land/Lease Documents"],
        "process": "Apply at District Industries Centre → Joint Director of Industries → State Level Committee",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Maharashtra"],
        "tags": ["manufacturing", "subsidy", "maharashtra"],
    },
    {
        "id": "nrlm",
        "name": "DAY-NRLM (Deendayal)",
        "full_name": "Deendayal Antyodaya Yojana — National Rural Livelihoods Mission",
        "description": "Builds strong institutions for the rural poor (Self-Help Groups) and provides financial inclusion, skill training and income-generation support.",
        "eligibility": [
            "Rural poor households, especially women",
            "Must form or join a Self-Help Group (SHG)",
            "BPL and APL households in rural areas",
        ],
        "benefits": [
            "Revolving Fund of ₹15,000 per SHG",
            "Community Investment Fund up to ₹2.5 lakhs",
            "Bank linkage loans at subsidised interest",
            "Interest subvention: women SHG loans at 7% (3% effective in many states)",
        ],
        "max_funding": 250000,
        "max_subsidy_percent": 0,
        "documents": ["Aadhaar", "SHG registration documents", "Passbook", "BPL card (if applicable)"],
        "process": "Join an SHG in your village → Participate for 3-6 months → Apply for Revolving Fund → Bank linkage",
        "categories": ["Women", "Agriculture", "MSME"],
        "states": ["All India"],
        "tags": ["women", "rural", "shg", "new_business"],
    },
    {
        "id": "nabard-ridf",
        "name": "NABARD Rural Loans",
        "full_name": "NABARD Kisan Credit Card & Rural MSME Finance",
        "description": "NABARD refinances rural and agri-allied businesses via commercial banks, RRBs and cooperative banks at concessional rates.",
        "eligibility": [
            "Farmers, agri-entrepreneurs, rural artisans",
            "Agri-allied businesses (dairy, poultry, fisheries, horticulture)",
            "Rural non-farm enterprises",
        ],
        "benefits": [
            "Kisan Credit Card: flexible credit up to ₹3 lakhs at 7% (4% effective with Interest Subvention)",
            "MSME loans in rural areas at concessional refinance rates",
            "Loans for FPO/cooperatives up to ₹5 crore",
        ],
        "max_funding": 30000000,
        "max_subsidy_percent": 0,
        "documents": ["Aadhaar", "Land Records / Khasra", "Kisan Credit Card application", "Bank account"],
        "process": "Apply at nearest commercial bank, RRB or cooperative bank for KCC or rural MSME loan backed by NABARD refinance",
        "categories": ["Agriculture", "MSME"],
        "states": ["All India"],
        "tags": ["agriculture", "rural", "kcc", "dairy", "fisheries"],
    },
    {
        "id": "wdc-mahila",
        "name": "Mahila Udyam Nidhi",
        "full_name": "Mahila Udyam Nidhi Scheme (SIDBI/PSBs)",
        "description": "Soft loan scheme to assist women entrepreneurs set up new small-scale industrial projects or rehabilitation of viable sick SSI units.",
        "eligibility": [
            "Women entrepreneurs in small-scale industries",
            "New projects or expansion of existing unit",
            "Project cost up to ₹10 lakhs",
        ],
        "benefits": [
            "Soft loan up to ₹10 lakhs with interest at 1% below prevailing rate",
            "Repayment up to 10 years including 5-year moratorium",
            "No collateral required for loans up to ₹5 lakhs under CGTMSE",
        ],
        "max_funding": 1000000,
        "max_subsidy_percent": 0,
        "documents": ["Aadhaar", "PAN", "Project Report", "Caste Certificate (if applicable)", "Quotations"],
        "process": "Apply to SBI, Punjab & Sind Bank, or SIDBI branches with complete project report",
        "categories": ["Women", "MSME", "Manufacturing"],
        "states": ["All India"],
        "tags": ["women", "new_business", "manufacturing"],
    },
    {
        "id": "cgtmse-plus",
        "name": "Credit Guarantee for Startups",
        "full_name": "Credit Guarantee Scheme for Startups (CGSS) — DPIIT",
        "description": "Provides credit guarantee to DPIIT-recognised startups for loans from member institutions without collateral.",
        "eligibility": [
            "DPIIT-recognised startup",
            "Loan from Scheduled Commercial Banks, NBFCs or SEBI-registered AIFs",
            "Loan up to ₹10 crore",
        ],
        "benefits": [
            "Credit guarantee cover up to 80% of the loan amount",
            "Collateral-free loans up to ₹10 crore",
            "Annual guarantee fee 2% per annum on outstanding credit",
        ],
        "max_funding": 100000000,
        "max_subsidy_percent": 0,
        "documents": ["DPIIT Recognition Certificate", "Incorporation Certificate", "Audited Financials / Projections", "Business Plan"],
        "process": "Apply through member lending institution (bank/NBFC) → CGSS guarantee issued → Loan disbursed",
        "categories": ["Startup"],
        "states": ["All India"],
        "tags": ["startup", "dpiit", "no_collateral"],
    },
    {
        "id": "rajasthan-msme",
        "name": "Rajasthan MSME Policy",
        "full_name": "Rajasthan Investment Promotion Scheme (RIPS) for MSMEs",
        "description": "Capital investment subsidy, interest subsidy and employment generation incentives for MSMEs setting up in Rajasthan.",
        "eligibility": [
            "New or expanding MSME units in Rajasthan",
            "Udyam-registered enterprises",
            "Manufacturing sector preferred",
        ],
        "benefits": [
            "Investment subsidy 6-10% of eligible fixed capital investment",
            "Interest subsidy 5% for 7 years (7% for women/SC/ST entrepreneurs)",
            "Electricity duty exemption for 7 years",
            "Stamp duty waiver",
        ],
        "max_funding": 5000000,
        "max_subsidy_percent": 10,
        "documents": ["Udyam Certificate", "Project Report", "Land Documents", "GST Registration"],
        "process": "Apply via rips.rajasthan.gov.in → DIC verification → State Industries Department approval",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Rajasthan"],
        "tags": ["manufacturing", "subsidy", "rajasthan"],
    },
    {
        "id": "up-msme",
        "name": "UP ODOP Scheme",
        "full_name": "Uttar Pradesh One District One Product (ODOP) Scheme",
        "description": "Promotes traditional industries and products unique to each district of Uttar Pradesh with financial support and market linkage.",
        "eligibility": [
            "Artisans and entrepreneurs working in their district's ODOP product",
            "MSMEs in manufacturing of identified ODOP products",
            "New units or expansion",
        ],
        "benefits": [
            "Capital subsidy 25% on eligible fixed capital (maximum ₹25 lakhs)",
            "Interest subsidy 7% for 5 years",
            "Skill development and design support",
            "Export promotion assistance",
        ],
        "max_funding": 2500000,
        "max_subsidy_percent": 25,
        "documents": ["Aadhaar", "Udyam Certificate", "Project Report", "Bank Statements"],
        "process": "Apply via odopup.in → District Industries Centre → State-level approval",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Uttar Pradesh"],
        "tags": ["manufacturing", "artisan", "odop", "up"],
    },
    {
        "id": "karnataka-msme",
        "name": "Karnataka Udyog Mitra",
        "full_name": "Karnataka Industrial Policy — MSME Incentives",
        "description": "Investment promotion for MSMEs in Karnataka with capital subsidy, interest subsidy and infrastructure support through Karnataka Udyog Mitra.",
        "eligibility": [
            "New or expanding MSME in Karnataka",
            "Udyam registration mandatory",
            "Manufacturing and select service sector units",
        ],
        "benefits": [
            "Investment subsidy 20-35% on eligible fixed capital (zone-based)",
            "Interest subsidy 5% for 5 years",
            "Power tariff concession",
            "KSSIDP sheds at subsidised rent",
        ],
        "max_funding": 10000000,
        "max_subsidy_percent": 35,
        "documents": ["Udyam Certificate", "GST Registration", "Project Report", "Land / Lease deed"],
        "process": "Apply at DIC / Udyog Mitra → Industries Commissioner approval → Subsidy disbursed after production",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Karnataka"],
        "tags": ["manufacturing", "subsidy", "karnataka"],
    },
    {
        "id": "atal-innovation",
        "name": "Atal Innovation Mission",
        "full_name": "Atal Innovation Mission (AIM) — NITI Aayog",
        "description": "Promotes innovation and entrepreneurship through Atal Incubation Centres, Atal Tinkering Labs and seed funding for deep-tech startups.",
        "eligibility": [
            "Startups and innovators at any stage",
            "Agri-tech, health-tech, edu-tech, fin-tech preferred focus areas",
            "Must apply to an AIM-affiliated Atal Incubation Centre",
        ],
        "benefits": [
            "Incubation support at AIC with funding up to ₹10 crore (to AIC)",
            "Seed grants to portfolio startups",
            "Mentoring, prototyping labs, market access",
        ],
        "max_funding": 10000000,
        "max_subsidy_percent": 0,
        "documents": ["DPIIT Recognition (preferred)", "Pitch Deck", "Business Plan", "Team CVs"],
        "process": "Apply to nearest Atal Incubation Centre at aim.gov.in → Selection process → Incubation support",
        "categories": ["Startup"],
        "states": ["All India"],
        "tags": ["startup", "tech", "incubation"],
    },
    {
        "id": "pmfme",
        "name": "PM FME Scheme",
        "full_name": "PM Formalisation of Micro Food Processing Enterprises (PM FME)",
        "description": "Provides credit-linked subsidy and technical support to existing unorganised food processing micro-enterprises to upgrade and formalise.",
        "eligibility": [
            "Existing micro food processing enterprise",
            "Individual, SHG, FPO, cooperative",
            "Annual turnover less than ₹1 crore",
        ],
        "benefits": [
            "Credit-linked capital subsidy 35% on eligible investment (up to ₹10 lakhs)",
            "Brand building and marketing support",
            "Capacity building and skill training",
            "Common infrastructure support for clusters",
        ],
        "max_funding": 1000000,
        "max_subsidy_percent": 35,
        "documents": ["Aadhaar", "FSSAI licence", "Udyam Certificate", "Bank Statements", "Project Report"],
        "process": "Apply at pmfme.mofpi.gov.in → District Resource Person support → Bank sanction → Subsidy claim",
        "categories": ["Agriculture", "Manufacturing", "MSME"],
        "states": ["All India"],
        "tags": ["food_processing", "manufacturing", "rural", "shg"],
    },
    {
        "id": "nef",
        "name": "NEF — North East Funding",
        "full_name": "North East Enterprise Development Scheme (NEEDS) / NEC grants",
        "description": "Special central assistance and concessional loans for enterprises in North Eastern states with higher subsidy rates and relaxed norms.",
        "eligibility": [
            "Enterprise located in any of the 8 North Eastern states",
            "Manufacturing or service sector MSME",
            "Udyam registration",
        ],
        "benefits": [
            "Higher subsidy rates (35-60%) under PMEGP, CGTMSE etc. for NE units",
            "Special term loans from NEDFI at competitive rates",
            "Transport subsidy on finished goods",
        ],
        "max_funding": 5000000,
        "max_subsidy_percent": 60,
        "documents": ["Udyam Certificate", "Address Proof", "Project Report", "Domicile Certificate"],
        "process": "Apply at State Industries Department or North East Development Finance Corporation (NEDFI)",
        "categories": ["MSME", "Manufacturing"],
        "states": ["Assam", "Meghalaya", "Manipur", "Mizoram", "Nagaland", "Arunachal Pradesh", "Tripura", "Sikkim"],
        "tags": ["northeast", "manufacturing", "high_subsidy"],
    },
]
